"""add github_repos table

Revision ID: 1366f1ade69a
Revises: 85d5aa7862de
Create Date: 2026-03-16 19:43:51.411957

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1366f1ade69a'
down_revision: Union[str, Sequence[str], None] = '85d5aa7862de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('github_repos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('repo_name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('stars', sa.Integer(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('updated_at', sa.String(), nullable=True),
    sa.Column('fetched_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_github_repos_id'), 'github_repos', ['id'], unique=False)
    op.create_index(op.f('ix_github_repos_username'), 'github_repos', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_github_repos_username'), table_name='github_repos')
    op.drop_index(op.f('ix_github_repos_id'), table_name='github_repos')
    op.drop_table('github_repos')
    # ### end Alembic commands ###
