"""add stock_quantity to items

Revision ID: 1f99401c9ac4
Revises: e77407dbf6a3
Create Date: 2026-02-20 12:14:58.373848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f99401c9ac4'
down_revision: Union[str, Sequence[str], None] = 'e77407dbf6a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('stock_quantity', sa.Integer(), nullable=False, server_default="0"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'stock_quantity')
    # ### end Alembic commands ###
