"""add created_at to items

Revision ID: 59193f288c00
Revises: 1f99401c9ac4
Create Date: 2026-02-20 16:01:34.887071

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59193f288c00'
down_revision: Union[str, Sequence[str], None] = '1f99401c9ac4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('created_at', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'created_at')
    # ### end Alembic commands ###
