"""change timestamp to datetime

Revision ID: 85d5aa7862de
Revises: 9c9609489ece
Create Date: 2026-03-15 15:01:41.607296

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85d5aa7862de'
down_revision: Union[str, Sequence[str], None] = '9c9609489ece'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "weather_data",
        "timestamp",
        existing_type=sa.VARCHAR(),
        type_=sa.DateTime(),
        postgresql_using='timestamp::timestamp'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('weather_data', 'timestamp',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    # ### end Alembic commands ###
