"""fix temperature column typo

Revision ID: 9c9609489ece
Revises: c7a4a0516889
Create Date: 2026-03-15 14:42:43.928695

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c9609489ece'
down_revision: Union[str, Sequence[str], None] = 'c7a4a0516889'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('weather_data', sa.Column('temperature', sa.Float(), nullable=False))
    op.drop_column('weather_data', 'temprature')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('weather_data', sa.Column('temprature', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_column('weather_data', 'temperature')
    # ### end Alembic commands ###
