"""remove created_at from items

Revision ID: 9f7acb79b130
Revises: f39740911350
Create Date: 2026-06-22 13:31:10.924551

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f7acb79b130'
down_revision: Union[str, Sequence[str], None] = 'f39740911350'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('created_at', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
