"""add crypto_prices table

Revision ID: c401f0ff80c1
Revises: 1366f1ade69a
Create Date: 2026-03-18 21:16:02.126745

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c401f0ff80c1'
down_revision: Union[str, Sequence[str], None] = '1366f1ade69a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crypto_prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('price_usd', sa.Float(), nullable=False),
    sa.Column('change_24h', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crypto_prices_id'), 'crypto_prices', ['id'], unique=False)
    op.create_index(op.f('ix_crypto_prices_symbol'), 'crypto_prices', ['symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_crypto_prices_symbol'), table_name='crypto_prices')
    op.drop_index(op.f('ix_crypto_prices_id'), table_name='crypto_prices')
    op.drop_table('crypto_prices')
    # ### end Alembic commands ###
