"""add weather_data table

Revision ID: c7a4a0516889
Revises: 59193f288c00
Create Date: 2026-03-15 13:50:57.808964

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7a4a0516889'
down_revision: Union[str, Sequence[str], None] = '59193f288c00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weather_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('temprature', sa.Float(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('humidity', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weather_data_id'), 'weather_data', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_weather_data_id'), table_name='weather_data')
    op.drop_table('weather_data')
    # ### end Alembic commands ###
